# Generated by Django 5.2 on 2025-04-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number'], name='user_otp_phone_n_82853c_idx'), models.Index(fields=['created_at'], name='user_otp_created_e091e0_idx')],
            },
        ),
    ]
